import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { requireEnv } from "./imap-connect";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12;

function getKey(): Buffer {
  const key = Buffer.from(requireEnv("CREDENTIAL_ENCRYPTION_KEY"), "base64");
  if (key.length !== 32) {
    throw new Error("CREDENTIAL_ENCRYPTION_KEY must decode to exactly 32 bytes (base64 of `openssl rand -base64 32`)");
  }
  return key;
}

/**
 * Encrypts a linked account's OAuth refresh token or IMAP password before
 * it's written to the database -- these are real, usable credentials for
 * someone's mailbox, not something to store in plaintext next to
 * everything else. AES-256-GCM with a random IV per call; the key comes
 * from CREDENTIAL_ENCRYPTION_KEY, generated once by the operator (`openssl
 * rand -base64 32`), never auto-generated by the app itself.
 */
export function encryptSecret(plaintext: string): string {
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, getKey(), iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return Buffer.concat([iv, authTag, ciphertext]).toString("base64");
}

export function decryptSecret(encoded: string): string {
  const raw = Buffer.from(encoded, "base64");
  const iv = raw.subarray(0, IV_LENGTH);
  const authTag = raw.subarray(IV_LENGTH, IV_LENGTH + 16);
  const ciphertext = raw.subarray(IV_LENGTH + 16);
  const decipher = createDecipheriv(ALGORITHM, getKey(), iv);
  decipher.setAuthTag(authTag);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
}
